name: coronavirus_rest_api_flutter_course
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   
  http: ^0.13.4
  provider: ^6.0.1
  intl: ^0.17.0
  shared_preferences: ^2.0.9
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appICON.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/virus.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

    - family: PantonBold
      fonts:
        - asset: assets/fonts/panton/Panton-BlackCaps.otf

    - family: PantonBoldItalic
      fonts:
        - asset: assets/fonts/panton/Panton-BlackitalicCaps.otf

    - family: Panton
      fonts:
        - asset: assets/fonts/panton/Panton-LightCaps.otf

    - family: PantonItalic
      fonts:
        - asset: assets/fonts/panton/Panton-LightitalicCaps.otf
